-- MySQL Script generated by MySQL Workbench
-- Tue Jan  7 04:57:55 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`InternaClinica`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`InternaClinica` ;

CREATE TABLE IF NOT EXISTS `mydb`.`InternaClinica` (
  `idInternaClinica` INT NOT NULL,
  `supervisor` VARCHAR(45) NULL,
  `fechaContratacion` DATETIME NULL,
  `horarios` VARCHAR(45) NULL,
  PRIMARY KEY (`idInternaClinica`),
  UNIQUE INDEX `idInternaClinica_UNIQUE` (`idInternaClinica` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`FirmaElectronica`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`FirmaElectronica` ;

CREATE TABLE IF NOT EXISTS `mydb`.`FirmaElectronica` (
  `idFirmaElec` INT NOT NULL,
  `firma` BLOB NULL,
  `fechaEmision` DATETIME NULL,
  `fechaExpiracion` DATETIME NULL,
  PRIMARY KEY (`idFirmaElec`),
  UNIQUE INDEX `idFirma_UNIQUE` (`idFirmaElec` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Usuario` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Usuario` (
  `idUsuario` INT NOT NULL,
  `identificacion` VARCHAR(11) NOT NULL,
  `nombres` VARCHAR(100) NOT NULL,
  `apellidos` VARCHAR(100) NOT NULL,
  `fechaNacimiento` DATETIME NOT NULL,
  `direccion` VARCHAR(200) NULL,
  `telefono` VARCHAR(15) NULL,
  `sexo` ENUM('F', 'M') NULL,
  `correo` VARCHAR(200) NULL,
  `estadoCivil` ENUM('S', 'C', 'U', 'D', 'V') NULL,
  `usuario` VARCHAR(100) NOT NULL,
  `contraseña` VARCHAR(200) NOT NULL,
  `fechaCreacion` DATETIME NULL,
  `fechaModificacion` DATETIME NULL,
  `especialidad` VARCHAR(100) NULL,
  `fotografia` BLOB NULL,
  `consultorio` VARCHAR(45) NULL,
  `estado` ENUM('Activo', 'Inactivo', 'Suspendido') NULL,
  `rol` ENUM('Admin', 'Doctor', 'Enfermera') NULL,
  `InternaClinica_idInternaClinica` INT NOT NULL,
  `FirmaElectronica_idFirmaElec` INT NOT NULL,
  PRIMARY KEY (`idUsuario`, `InternaClinica_idInternaClinica`, `FirmaElectronica_idFirmaElec`),
  UNIQUE INDEX `identificacion_UNIQUE` (`identificacion` ASC) VISIBLE,
  UNIQUE INDEX `idUsuarios_UNIQUE` (`idUsuario` ASC) VISIBLE,
  UNIQUE INDEX `usuario_UNIQUE` (`usuario` ASC) VISIBLE,
  UNIQUE INDEX `contraseña_UNIQUE` (`contraseña` ASC) VISIBLE,
  INDEX `fk_Usuario_InternaClinica1_idx` (`InternaClinica_idInternaClinica` ASC) VISIBLE,
  INDEX `fk_Usuario_FirmaElectronica1_idx` (`FirmaElectronica_idFirmaElec` ASC) VISIBLE,
  CONSTRAINT `fk_Usuario_InternaClinica1`
    FOREIGN KEY (`InternaClinica_idInternaClinica`)
    REFERENCES `mydb`.`InternaClinica` (`idInternaClinica`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Usuario_FirmaElectronica1`
    FOREIGN KEY (`FirmaElectronica_idFirmaElec`)
    REFERENCES `mydb`.`FirmaElectronica` (`idFirmaElec`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Formulario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Formulario` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Formulario` (
  `idFormulario` INT NOT NULL,
  `contenido` VARCHAR(45) NULL,
  `fechaCF` DATETIME NULL,
  `fechaModificacion` VARCHAR(45) NULL,
  `diagnostico` VARCHAR(45) NULL,
  `tratamiento` VARCHAR(45) NULL,
  `notas` VARCHAR(45) NULL,
  `observaciones` VARCHAR(45) NULL,
  PRIMARY KEY (`idFormulario`),
  UNIQUE INDEX `idFormulario_UNIQUE` (`idFormulario` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`HistoriaClinica`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`HistoriaClinica` ;

CREATE TABLE IF NOT EXISTS `mydb`.`HistoriaClinica` (
  `idHistoriaClinica` INT NOT NULL,
  `fechaCreacionHC` DATETIME NULL,
  `fechaUltimaEdicion` DATETIME NULL,
  PRIMARY KEY (`idHistoriaClinica`),
  UNIQUE INDEX `idHistoria Clinica_UNIQUE` (`idHistoriaClinica` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Paciente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Paciente` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Paciente` (
  `idPaciente` INT NOT NULL,
  `identificacion` VARCHAR(11) NOT NULL,
  `nombresP` VARCHAR(100) NULL,
  `apellidosP` VARCHAR(100) NULL,
  `fechaNacimiento` DATETIME NULL,
  `direccion` VARCHAR(200) NULL,
  `telefono` VARCHAR(15) NULL,
  `sexo` ENUM('F', 'M') NULL,
  `correo` VARCHAR(200) NULL,
  `estadoCivil` ENUM('S', 'C', 'U', 'D', 'V') NULL,
  `fechaRegistro` DATETIME NULL,
  `seguroMedico` VARCHAR(200) NULL,
  `alergias` VARCHAR(200) NULL,
  `grupoSanguineo` VARCHAR(3) NULL,
  `observaciones` VARCHAR(200) NULL,
  PRIMARY KEY (`idPaciente`),
  UNIQUE INDEX `idPaciente_UNIQUE` (`idPaciente` ASC) VISIBLE,
  UNIQUE INDEX `identificacion_UNIQUE` (`identificacion` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`HistorialAcceso`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`HistorialAcceso` ;

CREATE TABLE IF NOT EXISTS `mydb`.`HistorialAcceso` (
  `idHistorialAcceso` INT NOT NULL,
  `fecha_hora` DATETIME NULL,
  `accion` VARCHAR(45) NULL,
  `ip` VARCHAR(45) NULL,
  `idUsuario` VARCHAR(45) NULL,
  `Usuario_idUsuario` INT NOT NULL,
  PRIMARY KEY (`idHistorialAcceso`, `Usuario_idUsuario`),
  UNIQUE INDEX `idHistorialAcceso_UNIQUE` (`idHistorialAcceso` ASC) VISIBLE,
  INDEX `fk_HistorialAcceso_Usuario1_idx` (`Usuario_idUsuario` ASC) VISIBLE,
  CONSTRAINT `fk_HistorialAcceso_Usuario1`
    FOREIGN KEY (`Usuario_idUsuario`)
    REFERENCES `mydb`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Titulo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Titulo` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Titulo` (
  `idTitulo` INT NOT NULL,
  `nombreTitulo` VARCHAR(100) NULL,
  `institucionEducacionSuperior` VARCHAR(150) NULL,
  `tipoTitulo` ENUM('Nacional', 'Extranjero') NULL,
  `reconocidoPor` VARCHAR(100) NULL,
  `numeroRegistro` VARCHAR(45) NULL,
  `fechaRegistro` DATETIME NULL,
  `areaConocimiento` VARCHAR(50) NULL,
  `observacion` VARCHAR(200) NULL,
  `Usuario_idUsuario` INT NOT NULL,
  PRIMARY KEY (`idTitulo`, `Usuario_idUsuario`),
  UNIQUE INDEX `idtitulo_UNIQUE` (`idTitulo` ASC) VISIBLE,
  INDEX `fk_Titulo_Usuario1_idx` (`Usuario_idUsuario` ASC) VISIBLE,
  CONSTRAINT `fk_Titulo_Usuario1`
    FOREIGN KEY (`Usuario_idUsuario`)
    REFERENCES `mydb`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Certificaciones`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Certificaciones` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Certificaciones` (
  `idCertificaciones` INT NOT NULL,
  `nombreCertificacion` VARCHAR(45) NULL,
  `fechaEmisionC` DATETIME NULL,
  `fechaExpiracionC` DATETIME NULL,
  `idUsuario` VARCHAR(45) NULL,
  `Usuario_idUsuario` INT NOT NULL,
  PRIMARY KEY (`idCertificaciones`, `Usuario_idUsuario`),
  UNIQUE INDEX `idCertificaciones_UNIQUE` (`idCertificaciones` ASC) VISIBLE,
  UNIQUE INDEX `idUsuario_UNIQUE` (`idUsuario` ASC) VISIBLE,
  INDEX `fk_Certificaciones_Usuario1_idx` (`Usuario_idUsuario` ASC) VISIBLE,
  CONSTRAINT `fk_Certificaciones_Usuario1`
    FOREIGN KEY (`Usuario_idUsuario`)
    REFERENCES `mydb`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
