-- MySQL Script generated by MySQL Workbench
-- Wed Jan  8 19:47:06 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema clinica_sanjose
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `clinica_sanjose` ;

-- -----------------------------------------------------
-- Schema clinica_sanjose
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `clinica_sanjose` DEFAULT CHARACTER SET utf8 ;
USE `clinica_sanjose` ;

-- -----------------------------------------------------
-- Table `clinica_sanjose`.`FirmaElectronica`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `clinica_sanjose`.`FirmaElectronica` ;

CREATE TABLE IF NOT EXISTS `clinica_sanjose`.`FirmaElectronica` (
  `idFirmaElec` INT NOT NULL AUTO_INCREMENT,
  `firma` BLOB NULL,
  `fechaEmision` DATETIME NULL,
  `fechaExpiracion` DATETIME NULL,
  PRIMARY KEY (`idFirmaElec`),
  UNIQUE INDEX `idFirma_UNIQUE` (`idFirmaElec` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `clinica_sanjose`.`InternaClinica`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `clinica_sanjose`.`InternaClinica` ;

CREATE TABLE IF NOT EXISTS `clinica_sanjose`.`InternaClinica` (
  `idInternaClinica` INT NOT NULL AUTO_INCREMENT,
  `supervisor` VARCHAR(45) NULL,
  `fechaContratacion` DATETIME NULL,
  `horarios` VARCHAR(45) NULL,
  PRIMARY KEY (`idInternaClinica`),
  UNIQUE INDEX `idInternaClinica_UNIQUE` (`idInternaClinica` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `clinica_sanjose`.`Usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `clinica_sanjose`.`Usuario` ;

CREATE TABLE IF NOT EXISTS `clinica_sanjose`.`Usuario` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `identificacion` VARCHAR(11) NOT NULL,
  `nombres` VARCHAR(100) NOT NULL,
  `apellidos` VARCHAR(100) NOT NULL,
  `fechaNacimiento` DATETIME NOT NULL,
  `direccion` VARCHAR(200) NULL,
  `telefono` VARCHAR(15) NOT NULL,
  `sexo` ENUM('F', 'M') NOT NULL,
  `correo` VARCHAR(200) NOT NULL,
  `estadoCivil` ENUM('S', 'C', 'U', 'D', 'V') NULL,
  `usuario` VARCHAR(100) NOT NULL,
  `contraseña` VARCHAR(200) NOT NULL,
  `fechaCreacion` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `fechaModificacion` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `especialidad` VARCHAR(100) NOT NULL,
  `fotografia` BLOB NULL,
  `consultorio` VARCHAR(45) NULL,
  `estado` ENUM('Activo', 'Inactivo', 'Suspendido') NOT NULL,
  `rol` ENUM('Admin', 'Doctor', 'Enfermera') NOT NULL,
  `InternaClinica_idInternaClinica` INT NOT NULL,
  `FirmaElectronica_idFirmaElec` INT NOT NULL,
  `InternaClinica_idInternaClinica1` INT NOT NULL,
  PRIMARY KEY (`idUsuario`, `InternaClinica_idInternaClinica`, `FirmaElectronica_idFirmaElec`, `InternaClinica_idInternaClinica1`),
  UNIQUE INDEX `identificacion_UNIQUE` (`identificacion` ASC) VISIBLE,
  UNIQUE INDEX `idUsuarios_UNIQUE` (`idUsuario` ASC) VISIBLE,
  UNIQUE INDEX `usuario_UNIQUE` (`usuario` ASC) VISIBLE,
  UNIQUE INDEX `contraseña_UNIQUE` (`contraseña` ASC) VISIBLE,
  INDEX `fk_Usuario_FirmaElectronica1_idx` (`FirmaElectronica_idFirmaElec` ASC) VISIBLE,
  INDEX `fk_Usuario_InternaClinica1_idx` (`InternaClinica_idInternaClinica1` ASC) VISIBLE,
  CONSTRAINT `fk_Usuario_FirmaElectronica1`
    FOREIGN KEY (`FirmaElectronica_idFirmaElec`)
    REFERENCES `clinica_sanjose`.`FirmaElectronica` (`idFirmaElec`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Usuario_InternaClinica1`
    FOREIGN KEY (`InternaClinica_idInternaClinica1`)
    REFERENCES `clinica_sanjose`.`InternaClinica` (`idInternaClinica`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `clinica_sanjose`.`Paciente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `clinica_sanjose`.`Paciente` ;

CREATE TABLE IF NOT EXISTS `clinica_sanjose`.`Paciente` (
  `idPaciente` INT NOT NULL AUTO_INCREMENT,
  `identificacion` VARCHAR(11) NOT NULL,
  `apellidoParteno` VARCHAR(50) NULL,
  `apellidoMaterno` VARCHAR(50) NULL,
  `primerNombre` VARCHAR(50) NULL,
  `segundoNombre` VARCHAR(50) NULL,
  `direccionResidenciaHab` INT NULL,
  `barrio` VARCHAR(40) NULL,
  `parroquia` VARCHAR(40) NULL,
  `canton` VARCHAR(40) NULL,
  `provincia` VARCHAR(40) NULL,
  `zona` ENUM('U', 'R') NULL,
  `telefonoPaciente` VARCHAR(15) NULL,
  `fechaNacimiento` DATETIME NULL,
  `lugarNacimiento` VARCHAR(40) NULL,
  `nacionalidad` VARCHAR(40) NULL,
  `grupoCultural` VARCHAR(45) NULL,
  `sexo` ENUM('F', 'M') NULL,
  `estadoCivil` ENUM('Sol', 'Cas', 'U-L', 'Div', 'Viu') NULL,
  `instruccionUltimoAnioAprov` VARCHAR(45) NULL,
  `direccionPaciente` VARCHAR(200) NULL,
  `correo` VARCHAR(200) NULL,
  `fechaCreacion` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `ocupacion` VARCHAR(45) NULL,
  `empresaTrabajo` VARCHAR(45) NULL,
  `tipoSeguroSalud` VARCHAR(45) NULL,
  `alergias` VARCHAR(500) NULL,
  `grupoSanguineo` ENUM('O-', 'O+', 'A−', 'A+', 'B−', 'B+', 'AB−', 'AB+') NULL,
  `observaciones` VARCHAR(200) NULL,
  PRIMARY KEY (`idPaciente`),
  UNIQUE INDEX `idPaciente_UNIQUE` (`idPaciente` ASC) VISIBLE,
  UNIQUE INDEX `identificacion_UNIQUE` (`identificacion` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `clinica_sanjose`.`HistoriaClinica`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `clinica_sanjose`.`HistoriaClinica` ;

CREATE TABLE IF NOT EXISTS `clinica_sanjose`.`HistoriaClinica` (
  `idHistoriaClinica` INT NOT NULL AUTO_INCREMENT,
  `fechaCreacionHC` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `fechaUltimaEdicion` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `Paciente_idPaciente` INT NOT NULL,
  PRIMARY KEY (`idHistoriaClinica`, `Paciente_idPaciente`),
  UNIQUE INDEX `idHistoria Clinica_UNIQUE` (`idHistoriaClinica` ASC) VISIBLE,
  INDEX `fk_HistoriaClinica_Paciente1_idx` (`Paciente_idPaciente` ASC) VISIBLE,
  CONSTRAINT `fk_HistoriaClinica_Paciente1`
    FOREIGN KEY (`Paciente_idPaciente`)
    REFERENCES `clinica_sanjose`.`Paciente` (`idPaciente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `clinica_sanjose`.`Formulario_Tipo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `clinica_sanjose`.`Formulario_Tipo` ;

CREATE TABLE IF NOT EXISTS `clinica_sanjose`.`Formulario_Tipo` (
  `idFormulario_Tipo` INT NOT NULL AUTO_INCREMENT,
  `nroTipoFormulario` INT NULL,
  `nombreTipoFormulario` VARCHAR(150) NOT NULL,
  `Estructura` JSON NOT NULL,
  PRIMARY KEY (`idFormulario_Tipo`),
  UNIQUE INDEX `idFormulario_Tipo_UNIQUE` (`idFormulario_Tipo` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `clinica_sanjose`.`Formulario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `clinica_sanjose`.`Formulario` ;

CREATE TABLE IF NOT EXISTS `clinica_sanjose`.`Formulario` (
  `idFormulario` INT NOT NULL AUTO_INCREMENT,
  `institucionSistema` VARCHAR(45) NULL,
  `unicodigo` VARCHAR(45) NULL,
  `establecimeintoSalud` VARCHAR(45) NULL,
  `nroHistoriaClinica` VARCHAR(45) NULL,
  `tipoFormulario` VARCHAR(45) NULL,
  `fechaCreacionF` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `fechaUltimaModificacionF` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `contenido` JSON NULL,
  `estadoFormulario` ENUM('Abierto', 'Cerrado', 'Cancelado') NULL,
  `notas` VARCHAR(45) NULL,
  `observaciones` VARCHAR(45) NULL,
  `HistoriaClinica_idHistoriaClinica` INT NOT NULL,
  `HistoriaClinica_Paciente_idPaciente` INT NOT NULL,
  `Formulario_Tipo_idFormulario_Tipo` INT NOT NULL,
  PRIMARY KEY (`idFormulario`, `HistoriaClinica_idHistoriaClinica`, `HistoriaClinica_Paciente_idPaciente`, `Formulario_Tipo_idFormulario_Tipo`),
  UNIQUE INDEX `idFormulario_UNIQUE` (`idFormulario` ASC) VISIBLE,
  INDEX `fk_Formulario_HistoriaClinica1_idx` (`HistoriaClinica_idHistoriaClinica` ASC, `HistoriaClinica_Paciente_idPaciente` ASC) VISIBLE,
  INDEX `fk_Formulario_Formulario_Tipo1_idx` (`Formulario_Tipo_idFormulario_Tipo` ASC) VISIBLE,
  CONSTRAINT `fk_Formulario_HistoriaClinica1`
    FOREIGN KEY (`HistoriaClinica_idHistoriaClinica` , `HistoriaClinica_Paciente_idPaciente`)
    REFERENCES `clinica_sanjose`.`HistoriaClinica` (`idHistoriaClinica` , `Paciente_idPaciente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Formulario_Formulario_Tipo1`
    FOREIGN KEY (`Formulario_Tipo_idFormulario_Tipo`)
    REFERENCES `clinica_sanjose`.`Formulario_Tipo` (`idFormulario_Tipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `clinica_sanjose`.`Titulo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `clinica_sanjose`.`Titulo` ;

CREATE TABLE IF NOT EXISTS `clinica_sanjose`.`Titulo` (
  `idTitulo` INT NOT NULL AUTO_INCREMENT,
  `nombreTitulo` VARCHAR(100) NULL,
  `institucionEducacionSuperior` VARCHAR(150) NULL,
  `tipoTitulo` ENUM('Nacional', 'Extranjero') NULL,
  `reconocidoPor` VARCHAR(100) NULL,
  `numeroRegistro` VARCHAR(45) NULL,
  `fechaRegistro` DATETIME NULL,
  `areaConocimiento` VARCHAR(50) NULL,
  `observacion` VARCHAR(200) NULL,
  `Usuario_idUsuario` INT NOT NULL,
  PRIMARY KEY (`idTitulo`, `Usuario_idUsuario`),
  UNIQUE INDEX `idtitulo_UNIQUE` (`idTitulo` ASC) VISIBLE,
  INDEX `fk_Titulo_Usuario1_idx` (`Usuario_idUsuario` ASC) VISIBLE,
  CONSTRAINT `fk_Titulo_Usuario1`
    FOREIGN KEY (`Usuario_idUsuario`)
    REFERENCES `clinica_sanjose`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `clinica_sanjose`.`Certificaciones`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `clinica_sanjose`.`Certificaciones` ;

CREATE TABLE IF NOT EXISTS `clinica_sanjose`.`Certificaciones` (
  `idCertificaciones` INT NOT NULL AUTO_INCREMENT,
  `nombreCertificacion` VARCHAR(45) NULL,
  `fechaEmisionC` DATETIME NULL,
  `fechaExpiracionC` DATETIME NULL,
  `idUsuario` VARCHAR(45) NULL,
  `Usuario_idUsuario` INT NOT NULL,
  PRIMARY KEY (`idCertificaciones`, `Usuario_idUsuario`),
  UNIQUE INDEX `idCertificaciones_UNIQUE` (`idCertificaciones` ASC) VISIBLE,
  INDEX `fk_Certificaciones_Usuario1_idx` (`Usuario_idUsuario` ASC) VISIBLE,
  CONSTRAINT `fk_Certificaciones_Usuario1`
    FOREIGN KEY (`Usuario_idUsuario`)
    REFERENCES `clinica_sanjose`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `clinica_sanjose`.`Formulario_Log`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `clinica_sanjose`.`Formulario_Log` ;

CREATE TABLE IF NOT EXISTS `clinica_sanjose`.`Formulario_Log` (
  `idFormulario_Log` INT NOT NULL AUTO_INCREMENT,
  `fecha_Hora` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `accion` ENUM('Creacion', 'Modificacion') NULL,
  `camposModificados` JSON NULL,
  `notas` VARCHAR(200) NULL,
  `Usuario_idUsuario` INT NOT NULL,
  `Formulario_idFormulario` INT NOT NULL,
  PRIMARY KEY (`idFormulario_Log`, `Usuario_idUsuario`, `Formulario_idFormulario`),
  UNIQUE INDEX `idFormulario_Log_UNIQUE` (`idFormulario_Log` ASC) VISIBLE,
  INDEX `fk_Formulario_Log_Usuario1_idx` (`Usuario_idUsuario` ASC) VISIBLE,
  INDEX `fk_Formulario_Log_Formulario1_idx` (`Formulario_idFormulario` ASC) VISIBLE,
  CONSTRAINT `fk_Formulario_Log_Usuario1`
    FOREIGN KEY (`Usuario_idUsuario`)
    REFERENCES `clinica_sanjose`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Formulario_Log_Formulario1`
    FOREIGN KEY (`Formulario_idFormulario`)
    REFERENCES `clinica_sanjose`.`Formulario` (`idFormulario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `clinica_sanjose`.`Referido`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `clinica_sanjose`.`Referido` ;

CREATE TABLE IF NOT EXISTS `clinica_sanjose`.`Referido` (
  `idReferido` INT NOT NULL AUTO_INCREMENT,
  `nombreReferido` VARCHAR(45) NULL,
  `parentescoReferido` VARCHAR(45) NULL,
  `direccionReferido` VARCHAR(45) NULL,
  `telefonoReferido` VARCHAR(15) NULL,
  `Paciente_idPaciente` INT NOT NULL,
  PRIMARY KEY (`idReferido`, `Paciente_idPaciente`),
  INDEX `fk_Referido_Paciente1_idx` (`Paciente_idPaciente` ASC) VISIBLE,
  CONSTRAINT `fk_Referido_Paciente1`
    FOREIGN KEY (`Paciente_idPaciente`)
    REFERENCES `clinica_sanjose`.`Paciente` (`idPaciente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `clinica_sanjose`.`Usuario_has_HistoriaClinica`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `clinica_sanjose`.`Usuario_has_HistoriaClinica` ;

CREATE TABLE IF NOT EXISTS `clinica_sanjose`.`Usuario_has_HistoriaClinica` (
  `Usuario_idUsuario` INT NOT NULL,
  `Usuario_InternaClinica_idInternaClinica` INT NOT NULL,
  `Usuario_FirmaElectronica_idFirmaElec` INT NOT NULL,
  `Usuario_InternaClinica_idInternaClinica1` INT NOT NULL,
  `HistoriaClinica_idHistoriaClinica` INT NOT NULL,
  `HistoriaClinica_Paciente_idPaciente` INT NOT NULL,
  PRIMARY KEY (`Usuario_idUsuario`, `Usuario_InternaClinica_idInternaClinica`, `Usuario_FirmaElectronica_idFirmaElec`, `Usuario_InternaClinica_idInternaClinica1`, `HistoriaClinica_idHistoriaClinica`, `HistoriaClinica_Paciente_idPaciente`),
  INDEX `fk_Usuario_has_HistoriaClinica_HistoriaClinica1_idx` (`HistoriaClinica_idHistoriaClinica` ASC, `HistoriaClinica_Paciente_idPaciente` ASC) VISIBLE,
  INDEX `fk_Usuario_has_HistoriaClinica_Usuario1_idx` (`Usuario_idUsuario` ASC, `Usuario_InternaClinica_idInternaClinica` ASC, `Usuario_FirmaElectronica_idFirmaElec` ASC, `Usuario_InternaClinica_idInternaClinica1` ASC) VISIBLE,
  CONSTRAINT `fk_Usuario_has_HistoriaClinica_Usuario1`
    FOREIGN KEY (`Usuario_idUsuario` , `Usuario_InternaClinica_idInternaClinica` , `Usuario_FirmaElectronica_idFirmaElec` , `Usuario_InternaClinica_idInternaClinica1`)
    REFERENCES `clinica_sanjose`.`Usuario` (`idUsuario` , `InternaClinica_idInternaClinica` , `FirmaElectronica_idFirmaElec` , `InternaClinica_idInternaClinica1`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Usuario_has_HistoriaClinica_HistoriaClinica1`
    FOREIGN KEY (`HistoriaClinica_idHistoriaClinica` , `HistoriaClinica_Paciente_idPaciente`)
    REFERENCES `clinica_sanjose`.`HistoriaClinica` (`idHistoriaClinica` , `Paciente_idPaciente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
